-- ═══════════════════════════════════════════════════════════
-- FOUNDRY SEED DATA
-- Run this after schema.sql in Supabase SQL editor
-- ═══════════════════════════════════════════════════════════

-- ── COMPANIES ─────────────────────────────────────────────
insert into public.companies (id, slug, name, logo_letter, logo_color, tagline, about, website, stage, sector, hq, team_size, founded, raised, is_verified, investors, plan) values
  ('c0000001-0000-0000-0000-000000000001', 'kirana-club', 'Kirana Club', 'K', '#1A73E8',
   'Digitising India''s ₹50L cr kirana ecosystem',
   'Kirana Club is building the digital infrastructure for India''s 12 million kirana stores — powering payments, B2B ordering, and AI-driven demand forecasting.',
   'kiranaclub.com', 'Series B', 'B2B Commerce', 'Bengaluru', '80–150', '2019', '₹180Cr', true,
   ARRAY['Sequoia India','Lightspeed','Tiger Global','Accel India'], 'growth'),
  ('c0000002-0000-0000-0000-000000000002', 'setu', 'Setu', 'S', '#137333',
   'India''s financial data infrastructure',
   'APIs that power bank account verification, credit bureau pulls, and investment data for 300+ companies.',
   'setu.co', 'Series B', 'Fintech', 'Remote', '50–80', '2018', '₹120Cr', true, ARRAY['Lightspeed','Falcon Edge'], 'growth'),
  ('c0000003-0000-0000-0000-000000000003', 'zepto', 'Zepto', 'Z', '#B45309',
   '10-minute grocery delivery',
   'India''s fastest 10-minute grocery delivery platform with ₹7,000 crore in ARR.',
   'zepto.co', 'Series C', 'Quick Commerce', 'Mumbai', '500–1000', '2021', '₹3,000Cr', true, ARRAY['Y Combinator','Glade Brook','StepStone'], 'growth'),
  ('c0000004-0000-0000-0000-000000000004', 'razorpay', 'Razorpay', 'R', '#5B21B6',
   'India''s payment gateway unicorn',
   'Processes ₹10L crore in payments annually.',
   'razorpay.com', 'Series F', 'Fintech', 'Bengaluru', '3000+', '2014', '₹5,600Cr', true, ARRAY['Sequoia','GIC','Tiger Global'], 'growth'),
  ('c0000005-0000-0000-0000-000000000005', 'cred', 'CRED', 'C', '#111827',
   'Rewards for credit card payments',
   'India''s most sophisticated credit card rewards platform.',
   'cred.club', 'Series E', 'Fintech', 'Bengaluru', '500–1000', '2018', '₹4,000Cr', true, ARRAY['DST Global','Tiger Global','Sofina'], 'growth'),
  ('c0000006-0000-0000-0000-000000000006', 'browserstack', 'BrowserStack', 'B', '#E11D48',
   'World''s leading software testing platform',
   'Testing platform used by 50,000+ companies globally.',
   'browserstack.com', 'Series B', 'Developer Tools', 'Mumbai', '1000+', '2011', '₹1,500Cr', true, ARRAY['Accel','Bond Capital'], 'growth'),
  ('c0000007-0000-0000-0000-000000000007', 'phonepe', 'PhonePe', 'P', '#5B21B6',
   'India''s leading digital payments platform',
   'Serves 500M+ users with UPI payments.',
   'phonepe.com', 'Series E', 'Fintech', 'Bengaluru', '5000+', '2015', '₹12,000Cr', true, ARRAY['Walmart','General Atlantic'], 'growth'),
  ('c0000008-0000-0000-0000-000000000008', 'ola', 'Ola', 'O', '#2563EB',
   'India''s largest ride-hailing platform',
   'Serves 3M+ driver-partners across India. Also building Ola Electric.',
   'olacabs.com', 'Series J', 'Mobility', 'Bengaluru', '10000+', '2010', '₹25,000Cr', true, ARRAY['SoftBank','Tiger Global','Tencent'], 'growth'),
  ('c0000009-0000-0000-0000-000000000009', 'swiggy', 'Swiggy', 'S', '#f97316',
   'India''s food and grocery delivery leader',
   'From food delivery to Instamart — India''s largest hyperlocal delivery platform.',
   'swiggy.com', 'IPO', 'Food Delivery', 'Bengaluru', '5000+', '2014', 'IPO', true, ARRAY['SoftBank','Prosus','Accel'], 'growth'),
  ('c0000010-0000-0000-0000-000000000010', 'meesho', 'Meesho', 'M', '#7C3AED',
   'Social commerce for India',
   'India''s largest social commerce platform with 200M+ SKUs.',
   'meesho.com', 'Series F', 'E-commerce', 'Bengaluru', '2000+', '2015', '₹5,000Cr', true, ARRAY['SoftBank','Fidelity','B Capital'], 'growth'),
  ('c0000011-0000-0000-0000-000000000011', 'dunzo', 'Dunzo', 'D', '#059669',
   'Quick commerce and delivery',
   'Instant delivery platform rebuilding around dark stores and quick commerce.',
   'dunzo.com', 'Series D', 'Quick Commerce', 'Bengaluru', '500+', '2015', '₹800Cr', true, ARRAY['Reliance','Google'], 'growth'),
  ('c0000012-0000-0000-0000-000000000012', 'urban-company', 'Urban Company', 'U', '#6366f1',
   'Home services marketplace',
   'India''s leading home services platform.',
   'urbancompany.com', 'Series F', 'Home Services', 'Gurugram', '1000+', '2014', '₹2,000Cr', true, ARRAY['Tiger Global','Prosus','Vy Capital'], 'growth');

-- ── JOBS (12 from prototype JOBS array) ─────────────────
insert into public.jobs (id, company_id, title, type, location, work_type, salary_min, salary_max, salary_display, equity, description, responsibilities, requirements, skills, tags, perks, status) values
  ('j0000001-0000-0000-0000-000000000001', 'c0000001-0000-0000-0000-000000000001',
   'Senior Product Manager', 'product', 'Bengaluru', 'Hybrid', 28, 40, '₹28–40L', '0.1%',
   '<p>We''re looking for a Senior PM to own the core merchant-side product — the dashboard, onboarding, and payments flows that 12 million kirana stores interact with daily.</p><p>You''ll work directly with the CPO, lead a squad of 2 engineers and 1 designer, and ship every week.</p>',
   ARRAY['Own the merchant dashboard product end-to-end','Run weekly sprint reviews and fortnightly roadmap syncs','Define and track product KPIs; run A/B tests','Work with field team to understand kirana owner pain points','Collaborate with data team to build self-serve analytics'],
   ARRAY['3+ years as a PM at a consumer or B2B product company','Strong SQL skills','Experience owning a product with 500k+ active users','MBA from Tier 1 institution preferred','Prior commerce or fintech experience a plus'],
   ARRAY['Product Strategy','B2C','SQL','A/B Testing','Roadmapping','Figma','Data Analysis'],
   ARRAY['Product Strategy','B2C','SQL','Roadmapping'],
   ARRAY['Health insurance (family)','ESOP + equity','Hybrid 3 days/week','₹50K learning budget'],
   'live'),
  ('j0000002-0000-0000-0000-000000000002', 'c0000002-0000-0000-0000-000000000002',
   'Growth Lead', 'growth', 'Remote', 'Remote', 22, 32, '₹22–32L', 'ESOP',
   '<p>Setu builds India''s financial data infrastructure. We need a Growth Lead to own the full funnel from awareness to activation for our developer-facing products.</p>',
   ARRAY['Own MQL→SQL pipeline and optimise conversion','Build lifecycle email/in-app campaigns','Work with product to remove friction in API trial','Manage SEO, content, and paid channels'],
   ARRAY['4+ years in B2B growth or demand gen','Strong analytical skills — GA4, Amplitude, SQL','Experience with CRM tooling (HubSpot or Salesforce)','Understanding of API/developer products a plus'],
   ARRAY['B2B Growth','SQL','Analytics','HubSpot','Content Marketing','SEO'],
   ARRAY['Growth','B2B SaaS','Analytics','CRM'],
   ARRAY['Fully remote','ESOP','Health cover','Home office stipend'],
   'live'),
  ('j0000003-0000-0000-0000-000000000003', 'c0000003-0000-0000-0000-000000000003',
   'Head of Product', 'product', 'Mumbai', 'Hybrid', 40, 60, '₹40–60L', '0.15%',
   '<p>Zepto is India''s fastest 10-minute grocery delivery platform. We''re hiring a Head of Product to lead our consumer-facing app team.</p>',
   ARRAY['Lead a team of 6 PMs','Drive the roadmap for consumer app','Partner with CEO and CMO on growth strategy','Build world-class product culture'],
   ARRAY['6+ years of product experience, 2+ managing PMs','Track record shipping at scale (10M+ users)','Deep intuition for consumer behaviour and mobile UX'],
   ARRAY['Product Leadership','Consumer Mobile','Team Management','Roadmapping','0→1'],
   ARRAY['Product Leadership','Quick Commerce','0→1'],
   ARRAY['ESOP at Series C valuation','Relocation support','Top-of-market comp'],
   'live'),
  ('j0000004-0000-0000-0000-000000000004', 'c0000004-0000-0000-0000-000000000004',
   'Engineering Lead — Payments Core', 'engineering', 'Bengaluru', 'Hybrid', 35, 55, '₹35–55L', 'ESOP',
   '<p>Razorpay processes ₹10L crore in payments annually. We''re looking for an Engineering Lead for our payments core team.</p>',
   ARRAY['Lead a team of 8 engineers','Own reliability and scalability of payment settlement','Drive architectural decisions','Mentor engineers and run 1:1s'],
   ARRAY['6+ years backend engineering, 2+ in a lead role','Deep distributed systems experience','Strong Java/Kotlin; Kafka and microservices preferred'],
   ARRAY['Java','Distributed Systems','Kafka','Microservices','Tech Leadership'],
   ARRAY['Distributed Systems','Java','Payments','Tech Lead'],
   ARRAY['ESOP at unicorn valuation','₹1L BYOD allowance','Comprehensive health cover'],
   'live'),
  ('j0000005-0000-0000-0000-000000000005', 'c0000005-0000-0000-0000-000000000005',
   'Product Manager — Rewards', 'product', 'Bengaluru', 'On-site', 20, 30, '₹20–30L', 'ESOP',
   '<p>CRED''s rewards system is one of India''s most sophisticated loyalty programmes. We''re looking for a PM to own coins, cashback, and gamification.</p>',
   ARRAY['Own coins economy — earn rates, redemption, gamification','Design and run large-scale A/B experiments','Partner with data science for reward personalisation'],
   ARRAY['2–4 years as a PM in consumer or fintech','Strong quantitative background','Prior loyalty, gamification, or subscription experience'],
   ARRAY['Product Strategy','Loyalty','A/B Testing','SQL','Gamification'],
   ARRAY['Rewards','Loyalty','B2C','Experimentation'],
   ARRAY['ESOP','Unlimited leave','World-class design culture','Top comp'],
   'live'),
  ('j0000006-0000-0000-0000-000000000006', 'c0000006-0000-0000-0000-000000000006',
   'Growth Marketing Manager', 'growth', 'Mumbai', 'Hybrid', 16, 24, '₹16–24L', 'ESOP',
   '<p>BrowserStack is the world''s leading software testing platform. We need a Growth Marketing Manager for developer acquisition in India and APAC.</p>',
   ARRAY['Manage ₹2Cr+ monthly paid media budget','Build content and SEO strategy for developers','Run lifecycle campaigns to convert trials to paid'],
   ARRAY['3+ years in B2B growth or demand gen','Hands-on Google Ads, LinkedIn Ads, HubSpot','Understanding of developer audiences a plus'],
   ARRAY['Performance Marketing','SEO','HubSpot','Google Ads','LinkedIn Ads'],
   ARRAY['Performance Marketing','Developer Marketing','B2B SaaS'],
   ARRAY['ESOP','Hybrid work','₹50K learning budget'],
   'live'),
  ('j0000007-0000-0000-0000-000000000007', 'c0000007-0000-0000-0000-000000000007',
   'Senior Software Engineer — Android', 'engineering', 'Bengaluru', 'Hybrid', 22, 35, '₹22–35L', 'ESOP',
   '<p>PhonePe serves 500M+ users. Our Android team builds the fastest payments UX in India.</p>',
   ARRAY['Build and maintain critical features in the Android app','Optimise app performance','Work with product and design to ship pixel-perfect UX'],
   ARRAY['3+ years Android development with Kotlin','High-performance UI experience at scale','Strong CS fundamentals'],
   ARRAY['Kotlin','Android','Jetpack Compose','Performance Optimisation','Coroutines'],
   ARRAY['Android','Kotlin','Fintech','Mobile'],
   ARRAY['ESOP','Flexible hours','Health + wellness cover'],
   'live'),
  ('j0000008-0000-0000-0000-000000000008', 'c0000008-0000-0000-0000-000000000008',
   'Product Manager — Driver Platform', 'product', 'Bengaluru', 'Hybrid', 18, 28, '₹18–28L', 'ESOP',
   '<p>Ola''s driver platform serves 3M+ driver-partners. We''re looking for a PM for driver-side earnings, incentives, and support.</p>',
   ARRAY['Own driver earnings transparency','Design incentive structures','Reduce support contact rate through self-serve tooling'],
   ARRAY['2–4 years as a PM on a marketplace or platform product','Data-driven mindset with strong SQL','Empathy for the driver persona'],
   ARRAY['Platform Products','SQL','Incentive Design','B2C','Marketplace'],
   ARRAY['Platform','Driver Experience','Growth','B2C'],
   ARRAY['ESOP','Hybrid','Learning allowance'],
   'live'),
  ('j0000009-0000-0000-0000-000000000009', 'c0000009-0000-0000-0000-000000000009',
   'Senior Growth Manager', 'growth', 'Bengaluru', 'Hybrid', 20, 32, '₹20–32L', 'ESOP',
   '<p>Swiggy is looking for a Senior Growth Manager to own retention and reactivation.</p>',
   ARRAY['Own retention KPIs for core food delivery','Build CRM campaigns across push, email, in-app','Work with data science on churn prediction'],
   ARRAY['4+ years in growth or CRM at consumer internet','Hands-on MoEngage or CleverTap','Strong analytical skills'],
   ARRAY['CRM','Retention','MoEngage','A/B Testing','SQL'],
   ARRAY['Growth','Retention','CRM','B2C'],
   ARRAY['ESOP','Hybrid','Top comp','Free Swiggy One'],
   'live'),
  ('j0000010-0000-0000-0000-000000000010', 'c0000010-0000-0000-0000-000000000010',
   'Backend Engineer — Catalogue', 'engineering', 'Bengaluru', 'Hybrid', 18, 28, '₹18–28L', 'ESOP',
   '<p>Meesho''s catalogue team manages 200M+ SKUs. We need a backend engineer for indexing and search infrastructure.</p>',
   ARRAY['Build catalogue ingestion and enrichment pipeline','Improve search relevance using Elasticsearch','Own reliability of catalogue APIs for 50M+ users'],
   ARRAY['3+ years backend with Python or Go','Elasticsearch or similar search experience','Familiarity with large-scale data pipelines'],
   ARRAY['Python','Django','Elasticsearch','Kafka','PostgreSQL'],
   ARRAY['Python','Django','Elasticsearch','Backend'],
   ARRAY['ESOP','Hybrid','Health cover'],
   'live'),
  ('j0000011-0000-0000-0000-000000000011', 'c0000011-0000-0000-0000-000000000011',
   'Data Scientist — Demand Forecasting', 'data', 'Bengaluru', 'Hybrid', 20, 30, '₹20–30L', 'ESOP',
   '<p>Dunzo is rebuilding its demand forecasting stack. We need a Data Scientist for dark store demand prediction.</p>',
   ARRAY['Build time-series forecasting models','Own forecasting pipeline end-to-end','Collaborate with ops for actionable inventory plans'],
   ARRAY['3+ years applied ML with time-series focus','Strong Python and SQL','MLflow or similar preferred'],
   ARRAY['Python','Time Series','Machine Learning','SQL','MLflow'],
   ARRAY['ML','Time Series','Python','Forecasting'],
   ARRAY['ESOP','Hybrid','Flexible hours'],
   'live'),
  ('j0000012-0000-0000-0000-000000000012', 'c0000012-0000-0000-0000-000000000012',
   'Product Designer — Consumer', 'design', 'Gurugram', 'Hybrid', 16, 24, '₹16–24L', 'ESOP',
   '<p>Urban Company needs a Product Designer for consumer booking and discovery on mobile.</p>',
   ARRAY['Own end-to-end design for service booking flow','Build and maintain consumer design system','Run weekly usability tests'],
   ARRAY['3+ years product design at consumer mobile company','Strong Figma skills','Portfolio showing shipped mobile products'],
   ARRAY['Figma','Mobile UX','Design Systems','User Research','Prototyping'],
   ARRAY['Figma','Consumer UX','Mobile','Design Systems'],
   ARRAY['ESOP','Hybrid','Creative freedom','Design-led culture'],
   'live');

-- ── SAMPLE TALENT PROFILE ─────────────────────────────────
insert into public.talent_profiles (id, username, first_name, last_name, email, phone, city, headline, bio, current_role, current_company, years_of_experience, target_roles, skills, education, experience, work_preference, expected_salary_min, expected_salary_max, preferred_stage, availability, profile_score, is_open_to_roles) values
  ('t0000001-0000-0000-0000-000000000001', 'riya-menon', 'Riya', 'Menon', 'riya.menon@gmail.com', '+91 98765 43210', 'Bengaluru',
   'Senior Product Manager · B2C Growth · Bengaluru',
   'Senior PM with 5 years building consumer products at scale. Led the Swiggy One loyalty programme to 4M subscribers. Passionate about 0→1 product work and high-ownership roles at Series A–C startups where I can shape direction, not just execute.',
   'Senior Product Manager', 'Swiggy', 5,
   ARRAY['Senior Product Manager','Head of Product','VP Product'],
   ARRAY['Product Strategy','User Research','SQL','Data Analysis','A/B Testing','B2C Growth','Roadmapping','Stakeholder Management','Figma','Python (basics)'],
   '[{"degree":"MBA","field":"Marketing & Strategy","institution":"IIM Bangalore","year":"2018–2020"},{"degree":"B.Tech","field":"Computer Science","institution":"NIT Trichy","year":"2014–2018"}]'::jsonb,
   '[{"role":"Senior Product Manager","company":"Swiggy","type":"Full-time","period":"Jan 2021 – Present · 3 yrs","location":"Bengaluru","logo_color":"#f97316","logo_letter":"S","description":"Led Swiggy One loyalty programme from 0 to 4M subscribers. Owned the subscription product end-to-end."},{"role":"Product Manager","company":"Urban Company","type":"Full-time","period":"Jun 2018 – Dec 2020 · 2 yrs 6 mos","location":"Bengaluru","logo_color":"#6366f1","logo_letter":"U","description":"Built the service partner onboarding flow, reducing time-to-first-booking by 40%."}]'::jsonb,
   'hybrid', 28, 40, 'Series A–C', '1-month', 92, true);
